dist: trusty
sudo: false

language: go
go:
  - 1.11.x

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - travis_retry $HOME/gopath/bin/goveralls -service=travis-ci
